const COLLECTION_TYPES = {
  COLLECTION_DATA_LOADING: "COLLECTION_DATA_LOADING",
  COLLECTION_DATA_SUCCESS: "COLLECTION_DATA_SUCCESS",
  COLLECTION_DATA_ERROR: "COLLECTION_DATA_ERROR",
};
export default COLLECTION_TYPES;
